//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.MNBArfolyamServiceSoapClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mnb.hu/webservices/", ConfigurationName="MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap")]
    public interface MNBArfolyamServiceSoap {
        
        // CODEGEN: Generating message contract since the operation GetCurrencies is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencies", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        WebApp.MNBArfolyamServiceSoapClient.GetCurrenciesResponse GetCurrencies(WebApp.MNBArfolyamServiceSoapClient.GetCurrenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencies", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesResponse")]
        System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetCurrenciesResponse> GetCurrenciesAsync(WebApp.MNBArfolyamServiceSoapClient.GetCurrenciesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetCurrencyUnits is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnits", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        WebApp.MNBArfolyamServiceSoapClient.GetCurrencyUnitsResponse GetCurrencyUnits(WebApp.MNBArfolyamServiceSoapClient.GetCurrencyUnitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnits", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsResponse")]
        System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(WebApp.MNBArfolyamServiceSoapClient.GetCurrencyUnitsRequest request);
        
        // CODEGEN: Generating message contract since the operation GetCurrentExchangeRates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesStrin" +
            "gFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        WebApp.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesResponse GetCurrentExchangeRates(WebApp.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesRespo" +
            "nse")]
        System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync(WebApp.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetDateInterval is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateInterval", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        WebApp.MNBArfolyamServiceSoapClient.GetDateIntervalResponse GetDateInterval(WebApp.MNBArfolyamServiceSoapClient.GetDateIntervalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateInterval", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalResponse")]
        System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetDateIntervalResponse> GetDateIntervalAsync(WebApp.MNBArfolyamServiceSoapClient.GetDateIntervalRequest request);
        
        // CODEGEN: Generating message contract since the operation GetExchangeRates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        WebApp.MNBArfolyamServiceSoapClient.GetExchangeRatesResponse GetExchangeRates(WebApp.MNBArfolyamServiceSoapClient.GetExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesResponse")]
        System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetExchangeRatesResponse> GetExchangeRatesAsync(WebApp.MNBArfolyamServiceSoapClient.GetExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfo", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        WebApp.MNBArfolyamServiceSoapClient.GetInfoResponse GetInfo(WebApp.MNBArfolyamServiceSoapClient.GetInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfo", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoResponse")]
        System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetInfoResponse> GetInfoAsync(WebApp.MNBArfolyamServiceSoapClient.GetInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public Application.MNBArfolyamServiceSoapClient.GetCurrenciesRequestBody GetCurrencies;
        
        public GetCurrenciesRequest() {
        }
        
        public GetCurrenciesRequest(Application.MNBArfolyamServiceSoapClient.GetCurrenciesRequestBody GetCurrencies) {
            this.GetCurrencies = GetCurrencies;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrenciesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public Application.MNBArfolyamServiceSoapClient.GetCurrenciesResponseBody GetCurrenciesResponse1;
        
        public GetCurrenciesResponse() {
        }
        
        public GetCurrenciesResponse(Application.MNBArfolyamServiceSoapClient.GetCurrenciesResponseBody GetCurrenciesResponse1) {
            this.GetCurrenciesResponse1 = GetCurrenciesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public Application.MNBArfolyamServiceSoapClient.GetCurrencyUnitsRequestBody GetCurrencyUnits;
        
        public GetCurrencyUnitsRequest() {
        }
        
        public GetCurrencyUnitsRequest(Application.MNBArfolyamServiceSoapClient.GetCurrencyUnitsRequestBody GetCurrencyUnits) {
            this.GetCurrencyUnits = GetCurrencyUnits;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyUnitsResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public Application.MNBArfolyamServiceSoapClient.GetCurrencyUnitsResponseBody GetCurrencyUnitsResponse1;
        
        public GetCurrencyUnitsResponse() {
        }
        
        public GetCurrencyUnitsResponse(Application.MNBArfolyamServiceSoapClient.GetCurrencyUnitsResponseBody GetCurrencyUnitsResponse1) {
            this.GetCurrencyUnitsResponse1 = GetCurrencyUnitsResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public Application.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates;
        
        public GetCurrentExchangeRatesRequest() {
        }
        
        public GetCurrentExchangeRatesRequest(Application.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates) {
            this.GetCurrentExchangeRates = GetCurrentExchangeRates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public Application.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesResponseBody GetCurrentExchangeRatesResponse1;
        
        public GetCurrentExchangeRatesResponse() {
        }
        
        public GetCurrentExchangeRatesResponse(Application.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesResponseBody GetCurrentExchangeRatesResponse1) {
            this.GetCurrentExchangeRatesResponse1 = GetCurrentExchangeRatesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public Application.MNBArfolyamServiceSoapClient.GetDateIntervalRequestBody GetDateInterval;
        
        public GetDateIntervalRequest() {
        }
        
        public GetDateIntervalRequest(Application.MNBArfolyamServiceSoapClient.GetDateIntervalRequestBody GetDateInterval) {
            this.GetDateInterval = GetDateInterval;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateIntervalResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public Application.MNBArfolyamServiceSoapClient.GetDateIntervalResponseBody GetDateIntervalResponse1;
        
        public GetDateIntervalResponse() {
        }
        
        public GetDateIntervalResponse(Application.MNBArfolyamServiceSoapClient.GetDateIntervalResponseBody GetDateIntervalResponse1) {
            this.GetDateIntervalResponse1 = GetDateIntervalResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public Application.MNBArfolyamServiceSoapClient.GetExchangeRatesRequestBody GetExchangeRates;
        
        public GetExchangeRatesRequest() {
        }
        
        public GetExchangeRatesRequest(Application.MNBArfolyamServiceSoapClient.GetExchangeRatesRequestBody GetExchangeRates) {
            this.GetExchangeRates = GetExchangeRates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public Application.MNBArfolyamServiceSoapClient.GetExchangeRatesResponseBody GetExchangeRatesResponse1;
        
        public GetExchangeRatesResponse() {
        }
        
        public GetExchangeRatesResponse(Application.MNBArfolyamServiceSoapClient.GetExchangeRatesResponseBody GetExchangeRatesResponse1) {
            this.GetExchangeRatesResponse1 = GetExchangeRatesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public Application.MNBArfolyamServiceSoapClient.GetInfoRequestBody GetInfo;
        
        public GetInfoRequest() {
        }
        
        public GetInfoRequest(Application.MNBArfolyamServiceSoapClient.GetInfoRequestBody GetInfo) {
            this.GetInfo = GetInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public Application.MNBArfolyamServiceSoapClient.GetInfoResponseBody GetInfoResponse1;
        
        public GetInfoResponse() {
        }
        
        public GetInfoResponse(Application.MNBArfolyamServiceSoapClient.GetInfoResponseBody GetInfoResponse1) {
            this.GetInfoResponse1 = GetInfoResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MNBArfolyamServiceSoapChannel : WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MNBArfolyamServiceSoapClient : System.ServiceModel.ClientBase<WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap>, WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap {
        
        public MNBArfolyamServiceSoapClient() {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.MNBArfolyamServiceSoapClient.GetCurrenciesResponse WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap.GetCurrencies(WebApp.MNBArfolyamServiceSoapClient.GetCurrenciesRequest request) {
            return base.Channel.GetCurrencies(request);
        }
        
        public Application.MNBArfolyamServiceSoapClient.GetCurrenciesResponseBody GetCurrencies(Application.MNBArfolyamServiceSoapClient.GetCurrenciesRequestBody GetCurrencies1) {
            WebApp.MNBArfolyamServiceSoapClient.GetCurrenciesRequest inValue = new WebApp.MNBArfolyamServiceSoapClient.GetCurrenciesRequest();
            inValue.GetCurrencies = GetCurrencies1;
            WebApp.MNBArfolyamServiceSoapClient.GetCurrenciesResponse retVal = ((WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap)(this)).GetCurrencies(inValue);
            return retVal.GetCurrenciesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetCurrenciesResponse> WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap.GetCurrenciesAsync(WebApp.MNBArfolyamServiceSoapClient.GetCurrenciesRequest request) {
            return base.Channel.GetCurrenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetCurrenciesResponse> GetCurrenciesAsync(Application.MNBArfolyamServiceSoapClient.GetCurrenciesRequestBody GetCurrencies) {
            WebApp.MNBArfolyamServiceSoapClient.GetCurrenciesRequest inValue = new WebApp.MNBArfolyamServiceSoapClient.GetCurrenciesRequest();
            inValue.GetCurrencies = GetCurrencies;
            return ((WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap)(this)).GetCurrenciesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.MNBArfolyamServiceSoapClient.GetCurrencyUnitsResponse WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap.GetCurrencyUnits(WebApp.MNBArfolyamServiceSoapClient.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnits(request);
        }
        
        public Application.MNBArfolyamServiceSoapClient.GetCurrencyUnitsResponseBody GetCurrencyUnits(Application.MNBArfolyamServiceSoapClient.GetCurrencyUnitsRequestBody GetCurrencyUnits1) {
            WebApp.MNBArfolyamServiceSoapClient.GetCurrencyUnitsRequest inValue = new WebApp.MNBArfolyamServiceSoapClient.GetCurrencyUnitsRequest();
            inValue.GetCurrencyUnits = GetCurrencyUnits1;
            WebApp.MNBArfolyamServiceSoapClient.GetCurrencyUnitsResponse retVal = ((WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap)(this)).GetCurrencyUnits(inValue);
            return retVal.GetCurrencyUnitsResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetCurrencyUnitsResponse> WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap.GetCurrencyUnitsAsync(WebApp.MNBArfolyamServiceSoapClient.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(Application.MNBArfolyamServiceSoapClient.GetCurrencyUnitsRequestBody GetCurrencyUnits) {
            WebApp.MNBArfolyamServiceSoapClient.GetCurrencyUnitsRequest inValue = new WebApp.MNBArfolyamServiceSoapClient.GetCurrencyUnitsRequest();
            inValue.GetCurrencyUnits = GetCurrencyUnits;
            return ((WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap)(this)).GetCurrencyUnitsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesResponse WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap.GetCurrentExchangeRates(WebApp.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRates(request);
        }
        
        public Application.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesResponseBody GetCurrentExchangeRates(Application.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates1) {
            WebApp.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesRequest inValue = new WebApp.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesRequest();
            inValue.GetCurrentExchangeRates = GetCurrentExchangeRates1;
            WebApp.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesResponse retVal = ((WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRates(inValue);
            return retVal.GetCurrentExchangeRatesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesResponse> WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap.GetCurrentExchangeRatesAsync(WebApp.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync(Application.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates) {
            WebApp.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesRequest inValue = new WebApp.MNBArfolyamServiceSoapClient.GetCurrentExchangeRatesRequest();
            inValue.GetCurrentExchangeRates = GetCurrentExchangeRates;
            return ((WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.MNBArfolyamServiceSoapClient.GetDateIntervalResponse WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap.GetDateInterval(WebApp.MNBArfolyamServiceSoapClient.GetDateIntervalRequest request) {
            return base.Channel.GetDateInterval(request);
        }
        
        public Application.MNBArfolyamServiceSoapClient.GetDateIntervalResponseBody GetDateInterval(Application.MNBArfolyamServiceSoapClient.GetDateIntervalRequestBody GetDateInterval1) {
            WebApp.MNBArfolyamServiceSoapClient.GetDateIntervalRequest inValue = new WebApp.MNBArfolyamServiceSoapClient.GetDateIntervalRequest();
            inValue.GetDateInterval = GetDateInterval1;
            WebApp.MNBArfolyamServiceSoapClient.GetDateIntervalResponse retVal = ((WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap)(this)).GetDateInterval(inValue);
            return retVal.GetDateIntervalResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetDateIntervalResponse> WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap.GetDateIntervalAsync(WebApp.MNBArfolyamServiceSoapClient.GetDateIntervalRequest request) {
            return base.Channel.GetDateIntervalAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetDateIntervalResponse> GetDateIntervalAsync(Application.MNBArfolyamServiceSoapClient.GetDateIntervalRequestBody GetDateInterval) {
            WebApp.MNBArfolyamServiceSoapClient.GetDateIntervalRequest inValue = new WebApp.MNBArfolyamServiceSoapClient.GetDateIntervalRequest();
            inValue.GetDateInterval = GetDateInterval;
            return ((WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap)(this)).GetDateIntervalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.MNBArfolyamServiceSoapClient.GetExchangeRatesResponse WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap.GetExchangeRates(WebApp.MNBArfolyamServiceSoapClient.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRates(request);
        }
        
        public Application.MNBArfolyamServiceSoapClient.GetExchangeRatesResponseBody GetExchangeRates(Application.MNBArfolyamServiceSoapClient.GetExchangeRatesRequestBody GetExchangeRates1) {
            WebApp.MNBArfolyamServiceSoapClient.GetExchangeRatesRequest inValue = new WebApp.MNBArfolyamServiceSoapClient.GetExchangeRatesRequest();
            inValue.GetExchangeRates = GetExchangeRates1;
            WebApp.MNBArfolyamServiceSoapClient.GetExchangeRatesResponse retVal = ((WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap)(this)).GetExchangeRates(inValue);
            return retVal.GetExchangeRatesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetExchangeRatesResponse> WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap.GetExchangeRatesAsync(WebApp.MNBArfolyamServiceSoapClient.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetExchangeRatesResponse> GetExchangeRatesAsync(Application.MNBArfolyamServiceSoapClient.GetExchangeRatesRequestBody GetExchangeRates) {
            WebApp.MNBArfolyamServiceSoapClient.GetExchangeRatesRequest inValue = new WebApp.MNBArfolyamServiceSoapClient.GetExchangeRatesRequest();
            inValue.GetExchangeRates = GetExchangeRates;
            return ((WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap)(this)).GetExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.MNBArfolyamServiceSoapClient.GetInfoResponse WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap.GetInfo(WebApp.MNBArfolyamServiceSoapClient.GetInfoRequest request) {
            return base.Channel.GetInfo(request);
        }
        
        public Application.MNBArfolyamServiceSoapClient.GetInfoResponseBody GetInfo(Application.MNBArfolyamServiceSoapClient.GetInfoRequestBody GetInfo1) {
            WebApp.MNBArfolyamServiceSoapClient.GetInfoRequest inValue = new WebApp.MNBArfolyamServiceSoapClient.GetInfoRequest();
            inValue.GetInfo = GetInfo1;
            WebApp.MNBArfolyamServiceSoapClient.GetInfoResponse retVal = ((WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap)(this)).GetInfo(inValue);
            return retVal.GetInfoResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetInfoResponse> WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap.GetInfoAsync(WebApp.MNBArfolyamServiceSoapClient.GetInfoRequest request) {
            return base.Channel.GetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApp.MNBArfolyamServiceSoapClient.GetInfoResponse> GetInfoAsync(Application.MNBArfolyamServiceSoapClient.GetInfoRequestBody GetInfo) {
            WebApp.MNBArfolyamServiceSoapClient.GetInfoRequest inValue = new WebApp.MNBArfolyamServiceSoapClient.GetInfoRequest();
            inValue.GetInfo = GetInfo;
            return ((WebApp.MNBArfolyamServiceSoapClient.MNBArfolyamServiceSoap)(this)).GetInfoAsync(inValue);
        }
    }
}
